//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 02:21:22 PM CET 
//


package it.depositolegale.registroIngressi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import gov.loc.premis.v3.LinkingAgentIdentifierComplexType;
import gov.loc.premis.v3.ObjectIdentifierComplexType;
import gov.loc.premis.v3.OriginalNameComplexType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}id"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timeStampIngest"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}agentDepositor"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}originalContainerName"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}containerName"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}containerFingerPrint"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}containerFingerPrintChain" minOccurs="0"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}containerType"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}agentMachineIngest"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}agentSoftwareIngest"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}status"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timestampInit"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timestampElab"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timestampCoda"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timestampPub"/>
 *         &lt;element ref="{http://www.depositolegale.it/rgistroIngresso}timestampErr" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "timeStampIngest",
    "agentDepositor",
    "originalContainerName",
    "containerName",
    "containerFingerPrint",
    "containerFingerPrintChain",
    "containerType",
    "agentMachineIngest",
    "agentSoftwareIngest",
    "status",
    "timestampInit",
    "timestampElab",
    "timestampCoda",
    "timestampPub",
    "timestampErr"
})
@XmlRootElement(name = "mdRegistroIngressi")
public class MdRegistroIngressi {

    @XmlElement(required = true)
    protected ObjectIdentifierComplexType id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStampIngest;
    @XmlElement(required = true)
    protected LinkingAgentIdentifierComplexType agentDepositor;
    @XmlElement(required = true)
    protected OriginalNameComplexType originalContainerName;
    @XmlElement(required = true)
    protected OriginalNameComplexType containerName;
    @XmlElement(required = true)
    protected String containerFingerPrint;
    protected String containerFingerPrintChain;
    @XmlElement(required = true)
    protected BigInteger containerType;
    @XmlElement(required = true)
    protected LinkingAgentIdentifierComplexType agentMachineIngest;
    @XmlElement(required = true)
    protected LinkingAgentIdentifierComplexType agentSoftwareIngest;
    @XmlElement(required = true)
    protected BigInteger status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampInit;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampElab;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampCoda;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampPub;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestampErr;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectIdentifierComplexType }
     *     
     */
    public ObjectIdentifierComplexType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectIdentifierComplexType }
     *     
     */
    public void setId(ObjectIdentifierComplexType value) {
        this.id = value;
    }

    /**
     * Gets the value of the timeStampIngest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStampIngest() {
        return timeStampIngest;
    }

    /**
     * Sets the value of the timeStampIngest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStampIngest(XMLGregorianCalendar value) {
        this.timeStampIngest = value;
    }

    /**
     * Gets the value of the agentDepositor property.
     * 
     * @return
     *     possible object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public LinkingAgentIdentifierComplexType getAgentDepositor() {
        return agentDepositor;
    }

    /**
     * Sets the value of the agentDepositor property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public void setAgentDepositor(LinkingAgentIdentifierComplexType value) {
        this.agentDepositor = value;
    }

    /**
     * Gets the value of the originalContainerName property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalNameComplexType }
     *     
     */
    public OriginalNameComplexType getOriginalContainerName() {
        return originalContainerName;
    }

    /**
     * Sets the value of the originalContainerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalNameComplexType }
     *     
     */
    public void setOriginalContainerName(OriginalNameComplexType value) {
        this.originalContainerName = value;
    }

    /**
     * Gets the value of the containerName property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalNameComplexType }
     *     
     */
    public OriginalNameComplexType getContainerName() {
        return containerName;
    }

    /**
     * Sets the value of the containerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalNameComplexType }
     *     
     */
    public void setContainerName(OriginalNameComplexType value) {
        this.containerName = value;
    }

    /**
     * Gets the value of the containerFingerPrint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerFingerPrint() {
        return containerFingerPrint;
    }

    /**
     * Sets the value of the containerFingerPrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerFingerPrint(String value) {
        this.containerFingerPrint = value;
    }

    /**
     * Gets the value of the containerFingerPrintChain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerFingerPrintChain() {
        return containerFingerPrintChain;
    }

    /**
     * Sets the value of the containerFingerPrintChain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerFingerPrintChain(String value) {
        this.containerFingerPrintChain = value;
    }

    /**
     * Gets the value of the containerType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getContainerType() {
        return containerType;
    }

    /**
     * Sets the value of the containerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setContainerType(BigInteger value) {
        this.containerType = value;
    }

    /**
     * Gets the value of the agentMachineIngest property.
     * 
     * @return
     *     possible object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public LinkingAgentIdentifierComplexType getAgentMachineIngest() {
        return agentMachineIngest;
    }

    /**
     * Sets the value of the agentMachineIngest property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public void setAgentMachineIngest(LinkingAgentIdentifierComplexType value) {
        this.agentMachineIngest = value;
    }

    /**
     * Gets the value of the agentSoftwareIngest property.
     * 
     * @return
     *     possible object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public LinkingAgentIdentifierComplexType getAgentSoftwareIngest() {
        return agentSoftwareIngest;
    }

    /**
     * Sets the value of the agentSoftwareIngest property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkingAgentIdentifierComplexType }
     *     
     */
    public void setAgentSoftwareIngest(LinkingAgentIdentifierComplexType value) {
        this.agentSoftwareIngest = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    /**
     * Gets the value of the timestampInit property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampInit() {
        return timestampInit;
    }

    /**
     * Sets the value of the timestampInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampInit(XMLGregorianCalendar value) {
        this.timestampInit = value;
    }

    /**
     * Gets the value of the timestampElab property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampElab() {
        return timestampElab;
    }

    /**
     * Sets the value of the timestampElab property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampElab(XMLGregorianCalendar value) {
        this.timestampElab = value;
    }

    /**
     * Gets the value of the timestampCoda property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampCoda() {
        return timestampCoda;
    }

    /**
     * Sets the value of the timestampCoda property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampCoda(XMLGregorianCalendar value) {
        this.timestampCoda = value;
    }

    /**
     * Gets the value of the timestampPub property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampPub() {
        return timestampPub;
    }

    /**
     * Sets the value of the timestampPub property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampPub(XMLGregorianCalendar value) {
        this.timestampPub = value;
    }

    /**
     * Gets the value of the timestampErr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestampErr() {
        return timestampErr;
    }

    /**
     * Sets the value of the timestampErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestampErr(XMLGregorianCalendar value) {
        this.timestampErr = value;
    }

}
