//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.01 at 02:21:22 PM CET 
//


package it.depositolegale.registroIngressi;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import gov.loc.premis.v3.LinkingAgentIdentifierComplexType;
import gov.loc.premis.v3.ObjectIdentifierComplexType;
import gov.loc.premis.v3.OriginalNameComplexType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.depositolegale.rgistroingresso package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OriginalContainerName_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "originalContainerName");
    private final static QName _ContainerType_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "containerType");
    private final static QName _AgentSoftwareIngest_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "agentSoftwareIngest");
    private final static QName _ContainerName_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "containerName");
    private final static QName _TimeStampIngest_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timeStampIngest");
    private final static QName _TimestampErr_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timestampErr");
    private final static QName _ContainerFingerPrintChain_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "containerFingerPrintChain");
    private final static QName _TimestampInit_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timestampInit");
    private final static QName _TimestampPub_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timestampPub");
    private final static QName _AgentDepositor_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "agentDepositor");
    private final static QName _Id_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "id");
    private final static QName _ContainerFingerPrint_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "containerFingerPrint");
    private final static QName _TimestampCoda_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timestampCoda");
    private final static QName _Status_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "status");
    private final static QName _AgentMachineIngest_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "agentMachineIngest");
    private final static QName _TimestampElab_QNAME = new QName("http://www.depositolegale.it/rgistroIngresso", "timestampElab");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.depositolegale.rgistroingresso
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MdRegistroIngressi }
     * 
     */
    public MdRegistroIngressi createMdRegistroIngressi() {
        return new MdRegistroIngressi();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalNameComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "originalContainerName")
    public JAXBElement<OriginalNameComplexType> createOriginalContainerName(OriginalNameComplexType value) {
        return new JAXBElement<OriginalNameComplexType>(_OriginalContainerName_QNAME, OriginalNameComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "containerType")
    public JAXBElement<BigInteger> createContainerType(BigInteger value) {
        return new JAXBElement<BigInteger>(_ContainerType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkingAgentIdentifierComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "agentSoftwareIngest")
    public JAXBElement<LinkingAgentIdentifierComplexType> createAgentSoftwareIngest(LinkingAgentIdentifierComplexType value) {
        return new JAXBElement<LinkingAgentIdentifierComplexType>(_AgentSoftwareIngest_QNAME, LinkingAgentIdentifierComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginalNameComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "containerName")
    public JAXBElement<OriginalNameComplexType> createContainerName(OriginalNameComplexType value) {
        return new JAXBElement<OriginalNameComplexType>(_ContainerName_QNAME, OriginalNameComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timeStampIngest")
    public JAXBElement<XMLGregorianCalendar> createTimeStampIngest(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimeStampIngest_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timestampErr")
    public JAXBElement<XMLGregorianCalendar> createTimestampErr(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimestampErr_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "containerFingerPrintChain")
    public JAXBElement<String> createContainerFingerPrintChain(String value) {
        return new JAXBElement<String>(_ContainerFingerPrintChain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timestampInit")
    public JAXBElement<XMLGregorianCalendar> createTimestampInit(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimestampInit_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timestampPub")
    public JAXBElement<XMLGregorianCalendar> createTimestampPub(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimestampPub_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkingAgentIdentifierComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "agentDepositor")
    public JAXBElement<LinkingAgentIdentifierComplexType> createAgentDepositor(LinkingAgentIdentifierComplexType value) {
        return new JAXBElement<LinkingAgentIdentifierComplexType>(_AgentDepositor_QNAME, LinkingAgentIdentifierComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIdentifierComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "id")
    public JAXBElement<ObjectIdentifierComplexType> createId(ObjectIdentifierComplexType value) {
        return new JAXBElement<ObjectIdentifierComplexType>(_Id_QNAME, ObjectIdentifierComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "containerFingerPrint")
    public JAXBElement<String> createContainerFingerPrint(String value) {
        return new JAXBElement<String>(_ContainerFingerPrint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timestampCoda")
    public JAXBElement<XMLGregorianCalendar> createTimestampCoda(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimestampCoda_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "status")
    public JAXBElement<BigInteger> createStatus(BigInteger value) {
        return new JAXBElement<BigInteger>(_Status_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkingAgentIdentifierComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "agentMachineIngest")
    public JAXBElement<LinkingAgentIdentifierComplexType> createAgentMachineIngest(LinkingAgentIdentifierComplexType value) {
        return new JAXBElement<LinkingAgentIdentifierComplexType>(_AgentMachineIngest_QNAME, LinkingAgentIdentifierComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.depositolegale.it/rgistroIngresso", name = "timestampElab")
    public JAXBElement<XMLGregorianCalendar> createTimestampElab(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TimestampElab_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
