<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.depositolegale.it/webservice.checkMD"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:readInfoInputType="http://www.depositolegale.it/readInfoInput"
    xmlns:readInfoOutputType="http://www.depositolegale.it/readInfoOutput"
    xmlns:ws="http://www.depositolegale.it/webservice.checkMD">

    <!-- definizione dei tipi di dato utilizzati... questo dovrebbe ricordarvi qualcosa ;) -->
    <wsdl:types>
        <xs:schema xmlns:readInfoInputType="http://www.depositolegale.it/readInfoInput">
            <xs:import namespace="http://www.depositolegale.it/readInfoInput" schemaLocation="./Schema/ReadInfoInput.xsd"/>
        </xs:schema>
        <xs:schema xmlns:readInfoOutputType="http://www.depositolegale.it/readInfoOutput">
            <xs:import namespace="http://www.depositolegale.it/readInfoOutput" schemaLocation="./Schema/ReadInfoOutput.xsd"/>
        </xs:schema>
    </wsdl:types>
    
    <!-- definizione di uno dei messaggi impiegati dal web service per comunicare con l'applicazione client -->
    <wsdl:message name="CheckMDInput">
        <wsdl:part name="CheckMDInput" element="readInfoInputType:readInfoInput"/>
    </wsdl:message>
    <wsdl:message name="CheckMDOutput">
        <wsdl:part name="CheckMDOutput" element="readInfoOutputType:readInfoOutput"/>
    </wsdl:message>
    <!-- naturalmente può esistere più di un elemento message 
     all'interno del documento -->

    <wsdl:portType name="CheckMDPortType"> 
        <!-- definisce una "porta" e le operazioni che possono essere eseguite dal web service. 
            Definisce inoltre i messaggi coinvolti nelle operazioni elencate -->
        <wsdl:operation name="CheckMDOperation">
            <wsdl:input message="ws:CheckMDInput" name="CheckMDInput"/>
            <wsdl:output message="ws:CheckMDOutput" name="CheckMDOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="CheckMDBind" type="ws:CheckMDPortType"> 
        <!-- definisce il formato del messaggio ed i 
       dettagli di protocollo per ogni porta -->

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="CheckMDOperation">
            <soap:operation soapAction=""/>
            <wsdl:input name="CheckMDInput">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="CheckMDOutput">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="CheckMDService">
        <wsdl:port binding="ws:CheckMDBind" name="CheckMDPort">
            <soap:address location="http://localhost:8080/MagazziniDigitaliServices/services/CheckMDPort"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>