<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:userLibraryInputType="http://www.depositolegale.it/authenticationUserInput" xmlns:userLibraryOutputType="http://www.depositolegale.it/authenticationUserOutput" xmlns:ws="http://www.depositolegale.it/webservice.authenticationUserLibrary" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.depositolegale.it/webservice.authenticationUserLibrary">

    <!-- definizione dei tipi di dato utilizzati... questo dovrebbe ricordarvi qualcosa ;) -->
    <wsdl:types>
        <xs:schema xmlns:userLibraryInputType="http://www.depositolegale.it/login">
            <xs:import namespace="http://www.depositolegale.it/authenticationUserInput" schemaLocation="./Schema/Tools/UserLibraryInput.xsd"/>
        </xs:schema>
        <xs:schema xmlns:userLibraryOutputType="http://www.depositolegale.it/utenti">
            <xs:import namespace="http://www.depositolegale.it/authenticationUserOutput" schemaLocation="./Schema/Tools/UserLibraryOutput.xsd"/>
        </xs:schema>
    </wsdl:types>
    
    <!-- definizione di uno dei messaggi impiegati dal web service per comunicare con l'applicazione client -->
    <wsdl:message name="AuthenticationUserLibraryInput">
        <wsdl:part element="userLibraryInputType:authenticationUserInput" name="AuthenticationUserLibraryInput"/>
    </wsdl:message>
    <wsdl:message name="AuthenticationUserLibraryOutput">
        <wsdl:part element="userLibraryOutputType:authenticationUserOutput" name="AuthenticationUserLibraryOutput"/>
    </wsdl:message>
    <!-- naturalmente può esistere più di un elemento message 
     all'interno del documento -->

    <wsdl:portType name="AuthenticationUserLibraryPortType"> 
        <!-- definisce una "porta" e le operazioni che possono essere eseguite dal web service. 
            Definisce inoltre i messaggi coinvolti nelle operazioni elencate -->
        <wsdl:operation name="AuthenticationUserLibraryOperation">
            <wsdl:input message="ws:AuthenticationUserLibraryInput" name="AuthenticationUserLibraryInput"/>
            <wsdl:output message="ws:AuthenticationUserLibraryOutput" name="AuthenticationUserLibraryOutput"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="AuthenticationUserLibraryBind" type="ws:AuthenticationUserLibraryPortType"> 
        <!-- definisce il formato del messaggio ed i 
       dettagli di protocollo per ogni porta -->

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="AuthenticationUserLibraryOperation">
            <soap:operation soapAction=""/>
            <wsdl:input name="AuthenticationUserLibraryInput">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="AuthenticationUserLibraryOutput">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="AuthenticationUserLibraryService">
        <wsdl:port binding="ws:AuthenticationUserLibraryBind" name="AuthenticationUserLibraryPort">
            <soap:address location="http://localhost:8080/MagazziniDigitaliServices%23%232.0.19/services/AuthenticationUserLibraryPort"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
