<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:readInfoInputType="http://www.depositolegale.it/readInfoInput" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ws="http://www.depositolegale.it/webservice.confirmDelMD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.depositolegale.it/webservice.confirmDelMD">

    <!-- definizione dei tipi di dato utilizzati... questo dovrebbe ricordarvi qualcosa ;) -->
    <wsdl:types>
        <xs:schema>
            <xs:import namespace="http://www.depositolegale.it/readInfoInput" schemaLocation="./Schema/ReadInfoInput.xsd"/>
        </xs:schema>
    </wsdl:types>
    
    <!-- definizione di uno dei messaggi impiegati dal web service per comunicare con l'applicazione client -->
    <wsdl:message name="ConfirmDelMDInput">
        <wsdl:part element="readInfoInputType:readInfoInput" name="ConfirmDelMDInput"/>
    </wsdl:message>
    <!-- naturalmente può esistere più di un elemento message 
     all'interno del documento -->

    <wsdl:portType name="ConfirmDelMDPortType"> 
        <!-- definisce una "porta" e le operazioni che possono essere eseguite dal web service.
 Definisce inoltre i messaggi coinvolti nelle operazioni elencate -->
        <wsdl:operation name="ConfirmDelMDOperation">
            <wsdl:input message="ws:ConfirmDelMDInput" name="ConfirmDelMDInput"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="ConfirmDelMDBind" type="ws:ConfirmDelMDPortType"> 
        <!-- definisce il formato del messaggio ed i 
       dettagli di protocollo per ogni porta -->
        
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ConfirmDelMDOperation">
            <soap:operation soapAction=""/>
            <wsdl:input name="ConfirmDelMDInput">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="ConfirmDelMDService">
        <wsdl:port binding="ws:ConfirmDelMDBind" name="ConfirmDelMDPort">
            <soap:address location="http://localhost:8080/MagazziniDigitaliServices/services/ConfirmDelMDPort"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
