//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.29 at 08:41:10 PM CEST 
//


package info.lc.xmlns.premis_v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LOCTYPEDefinition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LOCTYPEDefinition">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ARK"/>
 *     &lt;enumeration value="URN"/>
 *     &lt;enumeration value="URL"/>
 *     &lt;enumeration value="PURL"/>
 *     &lt;enumeration value="HANDLE"/>
 *     &lt;enumeration value="DOI"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LOCTYPEDefinition")
@XmlEnum
public enum LOCTYPEDefinition {

    ARK,
    URN,
    URL,
    PURL,
    HANDLE,
    DOI,
    OTHER;

    public String value() {
        return name();
    }

    public static LOCTYPEDefinition fromValue(String v) {
        return valueOf(v);
    }

}
