//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.27 at 04:47:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "info:lc/xmlns/premis-v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.lc.xmlns.premis_v2;
