//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.29 at 08:41:10 PM CEST 
//


package it.depositolegale.md;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import info.lc.xmlns.premis_v2.AgentComplexType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bib" type="{http://www.depositolegale.it/MD}bib"/>
 *         &lt;element ref="{info:lc/xmlns/premis-v2}agent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bib",
    "agent"
})
@XmlRootElement(name = "md")
public class Md {

    @XmlElement(required = true)
    protected Bib bib;
    @XmlElement(namespace = "info:lc/xmlns/premis-v2")
    protected List<AgentComplexType> agent;

    /**
     * Gets the value of the bib property.
     * 
     * @return
     *     possible object is
     *     {@link Bib }
     *     
     */
    public Bib getBib() {
        return bib;
    }

    /**
     * Sets the value of the bib property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bib }
     *     
     */
    public void setBib(Bib value) {
        this.bib = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentComplexType }
     * 
     * 
     */
    public List<AgentComplexType> getAgent() {
        if (agent == null) {
            agent = new ArrayList<AgentComplexType>();
        }
        return this.agent;
    }

}
