//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.29 at 08:41:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.depositolegale.it/MD", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.depositolegale.md;
